name: Auto PR (feature -> main)
on:
  push:
    branches:
      - work-phase2
      - feat/*
      - fix/*
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Open or reuse PR to main
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = context.ref.replace('refs/heads/',''); // current branch
            const base = 'main';
            try {
              // List open PRs and filter in JS (base param isn't supported by the API list call)
              const { data: prs } = await github.rest.pulls.list({ owner, repo, state: 'open', per_page: 100 });
              const existing = prs.find(p => p.head.ref === head && p.base.ref === base);
              if (existing) {
                core.notice(`PR already exists: ${existing.html_url}`);
                return;
              }
              const { data: pr } = await github.rest.pulls.create({
                owner, repo, head, base,
                title: `auto-pr: ${head} -> ${base}`,
                body: 'Auto PR opened by workflow.'
              });
              core.notice(`PR created: ${pr.html_url}`);
            } catch (err) {
              core.setFailed(`auto-pr failed: ${err.message ?? err}`);
            }
