name: Auto PR (work-phase2 -> main)
on:
  push:
    branches: [ work-phase2 ]
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create or reuse PR
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = 'work-phase2';
            const base = 'main';
            const existing = await github.rest.pulls.list({
              owner, repo, state: 'open', head: `${owner}:${head}`, base
            });
            if (existing.data.length) {
              core.notice(`PR already exists: ${existing.data[0].html_url}`);
              return;
            }
            const pr = await github.rest.pulls.create({
              owner, repo, head, base,
              title: 'feat(ci/smoke): stable frontend build + vitest setup',
              body: 'Frontend build excludes tests via tsconfig.build.json; Vitest globals+jsdom configured; BE /healthz verified.'
            });
            core.notice(`PR created: ${pr.data.html_url}`);
