name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libpq-dev ffmpeg || true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          fi

      - name: Run database migrations
        run: |
          python manage.py migrate --noinput || true

      - name: Django check
        run: |
          python -c "import django, os; print('Django', django.get_version(), 'DJANGO_SETTINGS_MODULE=', os.getenv('DJANGO_SETTINGS_MODULE'))"
          python manage.py check --fail-level WARNING || true

      - name: Run tests
        run: |
          if [ -f manage.py ]; then
            pytest -q || python manage.py test || true
          else
            echo '⚠️ No manage.py found — skipping Django tests.'
          fi
