name: Backend CI
on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
      - "pyproject.toml"
      - "requirements*.txt"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
      - "pyproject.toml"
      - "requirements*.txt"
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Django checks
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
        run: python manage.py check
      - name: Ruff
        run: |
          pip install ruff
          ruff backend --output-format=github
      - name: mypy
        run: |
          pip install mypy django-stubs djangorestframework-stubs
          mypy backend
      - name: Pytest
        env:
          DJANGO_SETTINGS_MODULE: backend.settings
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pip install pytest pytest-django
          pytest -q
