name: frontend-ci
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - working-directory: frontend
        run: |
          npm ci || npm install
          npm run build || echo "No frontend yet"
